<?php
/**
 * Created by IntelliJ IDEA.
 * User: namnv
 * Time: 1:24 AM
 */

namespace Core\Helpers;

class NotificationType
{
    const __default = self::OK;

    const APPROVAL_REQUEST_DOCUMENT = "APPROVAL_REQUEST_DOCUMENT";
    const SIGN_REQUEST_DOCUMENT = "SIGN_REQUEST_DOCUMENT";
    const AGREE_APPROVAL_DOCUMENT = "AGREE_APPROVAL_DOCUMENT";
    const AGREE_SIGN_DOCUMENT = "AGREE_SIGN_DOCUMENT";
    const REMIND_APPROVAL_DOCUMENT = "REMIND_APPROVAL_DOCUMENT";
    const REMIND_SIGN_DOCUMENT = "REMIND_SIGN_DOCUMENT";
    const NEARLY_OVERDUE_DOCUMENT = "NEARLY_OVERDUE_DOCUMENT";
    const OVERDUE_DOCUMENT = "OVERDUE_DOCUMENT";
    const DENY_DOCUMENT = "DENY_DOCUMENT";
    const EXTEND_DOCUMENT = "EXTEND_DOCUMENT";
    const RESTORE_DOCUMENT = "RESTORE_DOCUMENT";
    const COMPLETE_DOCUMENT = "COMPLETE_DOCUMENT";
    const STORAGE_DOCUMENT = "STORAGE_DOCUMENT";
    const AUTHORISED_DOCUMENT = "AUTHORISED_DOCUMENT";
    const SEND_OTP_DOCUMENT = "SEND_OTP_DOCUMENT";
    const CREATE_COMPANY = "CREATE_COMPANY";
    const SEND_PASSWORD = "SEND_PASSWORD";
    const APPROVAL_REQUEST_ADDENDUM = "APPROVAL_REQUEST_ADDENDUM";
    const SIGN_REQUEST_ADDENDUM = "SIGN_REQUEST_ADDENDUM";
    const AGREE_APPROVAL_ADDENDUM = "AGREE_APPROVAL_ADDENDUM";
    const AGREE_SIGN_ADDENDUM = "AGREE_SIGN_ADDENDUM";
    const REMIND_APPROVAL_ADDENDUM = "REMIND_APPROVAL_ADDENDUM";
    const REMIND_SIGN_ADDENDUM = "REMIND_SIGN_ADDENDUM";
    const NEARLY_OVERDUE_ADDENDUM = "NEARLY_OVERDUE_ADDENDUM";
    const OVERDUE_ADDENDUM = "OVERDUE_ADDENDUM";
    const DENY_ADDENDUM = "DENY_ADDENDUM";
    const EXTEND_ADDENDUM = "EXTEND_ADDENDUM";
    const RESTORE_ADDENDUM = "RESTORE_ADDENDUM";
    const COMPLETE_ADDENDUM = "COMPLETE_ADDENDUM";
}
